Mountain.destroy_all

Mountain.create :name => 'Mount Everest', :image => 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Mount-Everest.jpg', :elevation => 8848, :location => '27°59′17″N 86°55′31″E', :description => 'Mount Everest, also known in Nepal as Sagarmāthā and in China as Chomolungma/珠穆朗玛峰, is Earth\'s highest mountain. Its peak is 8,848 metres (29,029 ft) above sea level. Mount Everest is located in the Mahalangur mountain range in Nepal. The international border between China (Tibet Autonomous Region) and Nepal runs across Everest\'s precise summit point. Its massif includes neighbouring peaks Lhotse, 8,516 m (27,940 ft); Nuptse, 7,855 m (25,771 ft) and Changtse, 7,580 m (24,870 ft).'

Mountain.create :name => 'K2', :image => 'https://upload.wikimedia.org/wikipedia/commons/1/12/K2_2006b.jpg', :elevation => 8611, :location => '35°52′53″N 76°30′48″E', :description => 'K2, also known as Mount Godwin-Austen or Chhogori (Balti: چھوغوری) is the second highest mountain in the world, after Mount Everest, at 8,611 metres (28,251 ft) above sea level. It is located on the China-Pakistan border between Baltistan, in the Gilgit–Baltistan region of northern Pakistan, and the Taxkorgan Tajik Autonomous County of Xinjiang, China. K2 is the highest point of the Karakoram range and the highest point in both Pakistan and Xinjiang.'

Mountain.create :name => 'Kangchenjunga', :image => 'https://upload.wikimedia.org/wikipedia/commons/1/19/Kanchenjunga_from_Tiger_Hills.JPG', :elevation => 8586, :location => '27°42′12″N 88°08′51″E', :description => 'Kangchenjunga (Nepali: कञ्चनजङ्घा; Hindi: कंचनजंघा; Sikkimese: ཁང་ཅེན་ཛོཾག་), also spelled Kanchenjunga, is the third highest mountain in the world, and lies partly in Nepal and partly in Sikkim, India. It rises with an elevation of 8,586 m (28,169 ft) in a section of the Himalayas called Kangchenjunga Himal that is limited in the west by the Tamur River, in the north by the Lhonak Chu and Jongsang La, and in the east by the Teesta River.'

Mountain.create :name => 'Lhotse', :image => 'https://upload.wikimedia.org/wikipedia/commons/7/72/Lhotse-fromChukhungRi.jpg', :elevation => 8516, :location => '27°57′42″N 86°55′59″E', :description => 'Lhotse (Nepali: ल्होत्से; Tibetan: ལྷོ་རྩེ) is the fourth highest mountain in the world at 8,516 metres (27,940 ft), after Mount Everest, K2, and Kangchenjunga. Part of the Everest massif, Lhotse is connected to the latter peak via the South Col. Lhotse means “South Peak” in Tibetan. In addition to the main summit at 8,516 metres (27,940 ft) above sea level, the mountain comprises the smaller peaks Lhotse Middle (East) at 8,414 m (27,605 ft), and Lhotse Shar at 8,383 m (27,503 ft). The summit is on the border between China, Tibet and the Khumbu region of Nepal.'

Mountain.create :name => 'Makalu', :image => 'https://upload.wikimedia.org/wikipedia/commons/1/19/Makalu.jpg', :elevation => 8485, :location => '27°53′23″N 87°05′20″E', :description => 'Makalu (Nepal: मकालु; China: Makaru) is the fifth highest mountain in the world at 8,485 metres (27,838 ft). It is located in the Mahalangur Himalayas 19 km (12 mi) southeast of Mount Everest, on the border between Nepal and China. One of the eight-thousanders, Makalu is an isolated peak whose shape is a four-sided pyramid.'
