Volcano.destroy_all
Volcano.create :name => 'Eyjafjallajökull', :country => 'Iceland'
Volcano.create :name => 'Mount Vesuvius', :country => 'Italy'
Volcano.create :name => 'Sakurajima', :country => 'Japan'
Volcano.create :name => 'Mount Merapi', :country => 'Indonesia'
Volcano.create :name => 'Mount Nyiragongo', :country => 'D.R of Congo'
Volcano.create :name => 'Ulawun', :country => 'Papua New Guinea'
Volcano.create :name => 'Taal Volcano', :country => 'Philippines'
Volcano.create :name => 'Mauna Loa', :country => 'Hawaii'
Volcano.create :name => 'Galeras', :country => 'Colombia'
Volcano.create :name => 'Santa María', :country => 'Guatemala'
